security:
    encoders:
        Build\UserBundle\Entity\Users:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: BuildUserBundle:Users, property: username }

    firewalls:
        # admin_area:
        #     pattern:    ^/admin
        #     http_basic: ~
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check

    access_control:
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/account/shop/bibz, roles: ROLE_USER }
        - { path: ^/hotel, roles: ROLE_USER }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/hotel, roles: ROLE_USER }